oxime/urls.py
from django.urls import path
from . import views

#from video_content.views import upload_video,display



app_name='oxime'

urlpatterns=[
    path('',views.index,name='index'),
    path('upload/',views.upload_data,name='upload'),
    path('display/',views.display,name='display'),
]

web/urls.py
from django import urls
from django.contrib import admin
from django.urls import path,include
from django.conf.urls.static import static
from django.conf import  settings


urlpatterns = [
    path('',include('oxime.urls')),
    path('admin/', admin.site.urls),
]
urlpatterns  += static(settings.STATIC_URL,document_root=settings.STATIC_ROOT)
urlpatterns += static(settings.MEDIA_URL,document_root=settings.MEDIA_ROOT)

oxime/models.py
from django.db import models

class Visitor(models.Model):
    def __str__(self):
        return self.name
    class Meta:
        ordering = ["name",'spo2','pulse']

    name=models.CharField(max_length=20)
    spo2=models.IntegerField(default=None)
    pulse=models.IntegerField(default=None)

oxime/forms.py
from .models import Videos
from django import forms

class VideoForm(forms.ModelForm):
    class Meta:
        model= Videos
        fields= ["title", "video"]

oxime/views.py
from django.shortcuts import render
from .models import Visitor
# Importing all necessary libraries
import numpy as np
import cv2
import os
import matplotlib.pyplot as plt
from scipy.signal import find_peaks
from django.core.files.storage import FileSystemStorage

def change(request):
    return render(request,'oxime/maintain.html')

def framegenerate(video_name):

    cam = cv2.VideoCapture(video_name)
    #frames = cam.get(cv2.CAP_PROP_FRAME_COUNT)
    #fps = int(cam.get(cv2.CAP_PROP_FPS))
    # calculate dusration of the video
    #seconds = int(frames / fps)
    #print(f"Video Duration ={seconds} sec")
    #try:
	    # creating a folder named data
	    #if not os.path.exists('data'):
		    #os.makedirs('data')
    # if not created then raise error
    #except OSError:
	    #print ('Error: Creating directory of data')
    # frame
    RED=np.array([])
    BLUE=np.array([])
    while(True):
	    # reading from frame
	    ret,frame = cam.read()
	    if ret:
                pic = frame
                a,b=0,0
                x=pic.shape[0]//2
                y=pic.shape[1]//2
                for i in range(x-10,x+10):
                    for j in range(y-10,y+10):
                        a=a+pic[i,j][0]
                        b=b+pic[i,j][2]
                t=400
                RED=np.append(RED,a/t)
                BLUE=np.append(BLUE,b/t)
	    else:
		    break
    a=100
    b=0.5
    ac_red=np.std(RED)
    dc_red=np.mean(RED)
    ac_blue=np.std(BLUE)
    dc_blue=np.mean(BLUE)
    #print(ac_red,dc_red,ac_blue,dc_blue)
    plt.plot(RED[10:])
    if os.path.exists("static/plot.jpg"):
        os.remove("static/plot.jpg")
    plt.savefig('static/plot.jpg')
    plt.close()
    pick=find_peaks(RED,distance = 13,height=dc_red-5)
    #print("picks at: ",pick[0])
    count=len(pick[0])
    #print("count =",count)
    #inplace seconds=20
    heart_beat=int((count*60)/20)
    #print("Pulse Rate =",heart_beat)

    if ac_blue==0:
        return "video is not prefect for spo2 detection",heart_beat
    spo2=(a-(b*((ac_red/dc_red)/(ac_blue/dc_blue))))
    #print("spo2 level =",spo2)
    cam.release()
    #cv2.destroyAllWindows()
    return spo2,heart_beat

def index(request):
    return render(request,'oxime/index.html',{'name':'raushan'})

# Create your views here.


def upload_data(request):
    process1=False
    process2=False
    if request.method == 'POST':

        uploaded_file = request.FILES['video']
        fs = FileSystemStorage()
        fs.save(uploaded_file.name, uploaded_file)
        process1=True
        name=request.POST['name']
        spo2,pulse=framegenerate('media/'+uploaded_file.name)
        try:
            q=Visitor(name=name,spo2=spo2,pulse=pulse)
            q.save()
        except:
            pass
        process2=True
        context={'process1':process1,'process2':process2,'name':name,'spo2':spo2,'pulse':pulse}

        dir = 'media'
        for f in os.listdir(dir):
            os.remove(os.path.join(dir, f))

        return render(request,'oxime/final.html',context)

    return render(request,'oxime/detail.html')


def display(request):

    d = Visitor.objects.all()
    context ={
        'data':d,
    }
    return render(request,'oxime/data.html',context)

oxime/templates/oxime/data.html
<div>
    <ol>
    {% for x in data %}
         <li> name={{x.name}}  </li>
            <ul>
                <li> spo2={{x.spo2}}   </li>
                <li> pulse={{x.pulse}} </li>
            </ul>
    {% endfor%}
</ol>
</div>

oxime/templates/oxime/detail.html
<form  method="POST" enctype="multipart/form-data">{% csrf_token %}
    <p>Name:-
        <input type="text" name="name" placeholder="Enter Your name">
    </p>
            
    <p>Video :-
        <input type="file" name="video" accept="video/*">
    </p>
        <input type="submit" /> 
</form>

oxime/templates/oxime/final.html
{% load static %}
{% if process1 %}
    <p>processed successfully..</p>
{% endif %}
{% if spo2 < 0 and pulse < 50 %}
<p><h2>Your video was not appropiate for detection .</h2></p>
<p> Ignore the result</p>
{% endif %}

{% if process2 %}
    <h1></h1>
    <h1></h1>
    <h1></h1>
    <p><strong>Hello {{name}} ,</strong><pre>
        Your result :-   </pre>
        <p>
            <img src="{% static 'plot.jpg' %}"  alt="Cardiogram" width="800" height="300">
        </p>
    </p>
    <p>
        <ul>
            <li>
               <h3>spo2 : {{spo2}}</h3>
            </li>
            <li>
                <h3>Pulse :{{pulse}}  </h3>
            </li>
        </ul>
    </p>
    <h1>
        Thanks!
    </h1>
{% endif %}

oxime/templates/oxime/index.html
<!doctype html>
<html lang="en">
    <head>
        <title>
            oxime
        </title>
    </head>
    <body>
    <h1>Welcome to oxime</h1>
    <h2>Hello user,<br>
    <pre>     In this application, I propose to use a mobile phone’s camera to estimate two vital cardiovascular parameters namely,
         pulse oximeter (SpO2) level and pulse-rate.
    </pre>
    </h2>
    <h1></h1>
    <h2>
        Steps :
    </h2>
    <p>
        <ol>
            <li>
                click next on the bottom of current page and enter your name and post your video.
            </li>
            <li>
                Place your index finger on mobile's back camera and record a video of approx 20 second by turning on your flashlight.
            </li>
            <li>
                <srtong>Don't choose the prerecoded file do current recording by choosing camcorder option.</srtong>
            </li>
            <li>
                After submitting your video, wait for a time for uploading and processing. (may take couple of minutes depends upon file size)
            </li>
            <li>
                After uploading you will be redirected to result page.
            </li>
        </ol>
    </p>
    <p>
        <h3>
            Instruction :-
        </h3>
        <ul>
            <li>
                <strong>
                    Don't move your finger during recording the video and don't keep space between finger and flashlight.
                </strong>
            </li>
            <li>
                If your video size is higher than 50 MB then program will terminate automatically due to server storage limit.
            </li>
            <li>
                Try to keep video size low as possible by setting up your recording quality for this purpose.
            </li>
            <li>
                The result will depend upon the video you are posting.
            </li>
            <li>
                The results from the developed application follow very closely with standard devices and this is valid for all the ranges of SpO2 values.
            </li>
            <li>
                <strong>
                    This application is alternative of oximeter, this is not replacable.
                </strong>
            </li>
            <li>
                <strong>
                <ul>
                        Accuracy:
                    <li> spo2 having 99.4%</li>
                    <li>pulse rate having 80%</li>
                </ul>
                </strong>
            </li>
        </ul>
    </p>
    <form>
        <h1>
        </h1>
       <h1><input  style="width: 150px; height: 80px;" type="button" onclick="location.href='{% url 'oxime:upload' %}'; return false;"value="next"></h1>
    </form>
    </body>
</html>

oxime/templates/oxime/maintain.html
<h2>
    Server under maintainance...........contact nirala161@gmail.com
</h2>